import { Topic } from './research';


export const TOPICS: Topic[] = [
    { code: 'T&D', name: 'Training & Development', publications: [
        { code: 'T&D', bookbool: false, authors: 'Quartiroli, A., Wagstaff, C. R. D., Herms, M. **, & Kemmel, C.**', year: '2021', article: 'The future of Continuing Education and Lifelong Learning in Sport and Exercise Psychology: A Delphi study.', periodical: 'Professional Psychology: Research and Practice', volume: '52', issue: '(2),', editors: '', book: '', pages: '173–185.', publisher: '', link: 'https://doi.org/fdn5'},
        { code: 'T&D', bookbool: false, authors: 'Hings, R. F., Wagstaff, C. R. D., Thelwell, R. C., Gilmore, S., & Anderson, V', year: '2020', article: 'Better preparing sports psychologists for the demands of applied practice: The emotional labor training gap.', periodical: 'Journal of Applied Sport Psychology', volume: '', issue: '' , editors: '', book: '', pages: '1-22.', publisher: '', link: ''},
        { code: 'T&D', bookbool: false, authors: 'Wagstaff, C. R., D. & Quartiroli, A.', year: '2020', article: 'Psychologists in search of an identity: Who are we?', periodical: 'Journal of Sport Psychology in Action', volume: '11', issue: '(4),', editors: '', book: '', pages: '254-265.', publisher: '', link: 'https://doi.org/fdn9'},
        { code: 'T&D', bookbool: false, authors: 'Quartiroli, A., Harris, B. S., Brückner, S., Chow, G. M., Connole, I. J., Cropley, B., Fogaça, J., Gonzalez, S. P., Guicciardi, M., Hau, A., Kao, S., Kavanagh, E. J., Keegan, R. J., Li, H. Y., Martin, G., Moyle, G. M., Noce, F., Peterson, K., Roy, J., Rubio, V. J., Wagstaff, C. R. D., Wong, R., Yousuf, S., & Zito, M.', year: '2020', article: ' The International Society of Sport Psychology Registry (ISSP-R) Ethical Code for Sport Psychology Practice.', periodical: 'International Journal of Sport and Exercise Psychology', volume: '', issue: '', editors: '', book: '', pages: '', publisher: '', link: 'https://doi.org/f7bm'},
        { code: 'T&D', bookbool: false, authors: 'Fogaca, J. L., Watson, J. W., & Zizzi, S. J.', year: '2020', article: 'The journey of service delivery competence in applied sport psychology: The arc of development for new professionals.', periodical: 'Journal of Clinical Sport Psychology', volume: '14,', issue: '', editors: '', book: '', pages: '126-129.', publisher: '', link: 'https://doi.org/gh4r'},
        { code: 'T&D', bookbool: false, authors: 'Fogaca, J. L., Koppang, R., & Zizzi, S. J.', year: '2018', article: 'Three pathways to supervision in applied sport psychology: Challenges and strategies to deliver effective supervision in graduate programs.', periodical: 'Journal of Sport Psychology in Action', volume: '', issue: '', editors: '', book: '', pages: '', publisher: '', link: 'https://doi.org/dwjh'},
        { code: 'T&D', bookbool: false, authors: 'Fogaca, J. L., Zizzi, S. J., Andersen, M. B. ', year: '2018', article: 'Walking multiple paths of supervision in American sport psychology: A qualitative tale of novice supervisees’ development.', periodical: 'The Sport Psychologist', volume: '32,', issue: '', editors: '', book: '', pages: '156-165.', publisher: '', link: 'https://doi.org/gdtjhr'},
        { code: 'T&D', bookbool: true, authors: 'Zizzi, S. J., & Fogaca, J. L.', year: '2018', article: 'Supervision in exercise settings.', periodical: '', volume: '', issue: '', editors: '', book: 'Oxford Research Encyclopedia of Sport and Exercise Psychology', pages: '', publisher: 'Oxford University Press', link: 'https://doi.org/gh4s'},
        { code: 'T&D', bookbool: true, authors: 'Fogaca, J. L.& Lee, S.', year: '2016', article: "Multicultural supervision: Experiences in an international master's program.", periodical: '', volume: '', issue: '', editors: 'J. G. Cremades & L. S. Tashman (Eds.),', book: 'Global practices and training in applied sport, exercise, and performance psychology: A case study approach', pages: '(pp. 307-314)', publisher: 'London, UK: Psychology Press', link: ''}
    ]},
    { code: 'P', name: 'Practice', publications: [
        { code: 'P', bookbool: false, authors: 'Cropley, B., Hanton, S., Miles, A., Niven, A., & Dohme, L-C.', year: '2020', article: 'Developing the effectiveness of applied sport psychology service delivery: A reflective practice intervention.', periodical: 'Sport & Exercise Psychology Review', volume: '16,', issue: '', editors: '', book: '', pages: '38-60.', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Terry, P. C., Parsons-Smith, R. L., Quartiroli, A., & Blackmore, S.', year: 'year', article: 'Publishing Trends in the International Journal of Sport Psychology During the First 50 Years (1970–2019), with a Particular Focus on Asia and Oceania.', periodical: 'International Journal of Sport Psychology', volume: '59,', issue: '', editors: '', book: '', pages: '493-513.', publisher: '', link: 'https://doi.org/f7bh'},
        { code: 'P', bookbool: false, authors: 'Price, D., Wagstaff, C. R. D., & Thelwell, R. C.', year: '2020', article: 'Opportunities and Considerations of New Media and Technology in Sport Psychology Service Delivery.', periodical: 'Journal of Sport Psychology in Action', volume: '', issue: '', editors: '', book: '', pages: '1-12.', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Sly, D., Mellalieu, S. D., & Wagstaff, C. R. D.', year: '2020', article: '“It’s psychology Jim, but not as we know it!”: The changing face of applied sport psychology practice.', periodical: 'Sport, Exercise & Performance Psychology', volume: '9,', issue: '', editors: '', book: '', pages: '87-101.', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Huntley, E., Cropley, B., Knowles, Z., & Miles, A.', year: '2019', article: 'The BASES expert statement on reflective practice: The key to experiential learning.', periodical: 'The Sport & Exercise Scientist', volume: '60,', issue: '', editors: '', book: '', pages: '6-7.', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Wagstaff, C. R. D. & Hays, K.', year: '2019', article: '“What have the Roman’s ever done for us?”: Stakeholder perspectives on 10 years of the Qualification in Sport and Exercise Psychology.', periodical: 'Sport & Exercise Psychology Review', volume: '15,', issue: '', editors: '', book: '', pages: '32-37.', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Bowley, C., Cropley, B., Neil, R., & Hanton, S., & Mitchell, I.', year: '2018', article: 'A life skills development programme for youth football: Programme development and preliminary evaluation.', periodical: 'Sport & Exercise Psychology Review', volume: '14,', issue: '', editors: '', book: '', pages: '3-22.', publisher: '', link: ''},
        { code: 'P', bookbool: true, authors: 'Swann, C., Keegan R., Cropley, B., & Mitchell, I.', year: '2018', article: 'Professional philosophy.', periodical: '', volume: '', issue: '', editors: 'G. Cremades & A. Mugford (Eds.),', book: 'Sport, exercise, and performance psychology: Theories and Applications', pages: '(pp. 15-33)', publisher: 'Routledge / Psychology Press', link: ''},
        { code: 'P', bookbool: true, authors: 'Neil, R., & Cropley, B.', year: '2017', article: 'Sport psychology across youth contexts.', periodical: '', volume: '', issue: '', editors: 'C. Knight, C. Harwood, & D. Gould (Eds.), ', book: 'Applying Sport & Exercise Psychology in Youth Sport', pages: '(pp. 29-45)', publisher: 'Routledge / Psychology Press', link: ''},
        { code: 'P', bookbool: false, authors: 'Picknell, G., Cropley, B., Mellalieu, S. D., & Hanton, S.', year: '2016', article: 'Investigating the benefits of enhancing reflective skills on the practice behaviours of health practitioners.', periodical: 'The Sport & Exercise Scientist', volume: '50,', issue: '', editors: '', book: '', pages: '22-23.', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Queiroz, F. S., Fogaca, J. L., Hanrahan, S. J., Zizzi, S. J.', year: '2016', article: ' Sport psychology in Brazil: Reflections on the past, present, and future of the field.', periodical: 'International Journal of Sport and Exercise Psychology', volume: '', issue: '', editors: '', book: '', pages: '1-18.', publisher: '', link: 'doi:10.1080/1612197X.2016.1154090'},
        { code: 'P', bookbool: true, authors: 'Cropley, B., & Neil, R.', year: '2016', article: 'Supervising from the swampy lowlands: A case study of collaborative approaches to supervision.', periodical: '', volume: '', issue: '', editors: 'L. Tashman & G. Cremades (Eds.),', book: 'Global practices and training in applied, sport, exercise, and performance psychology: A case study approach ', pages: '(pp.221-229)', publisher: 'Routledge / Psychology Press', link: ''},
        { code: 'P', bookbool: false, authors: 'Huntley, E., Cropley, B., Gilbourne, D., Knowles, Z., & Sparkes, A.', year: '2014', article: 'Reflecting back and forwards: The ebb and flow of reflective practice peer-reviewed research in sport.', periodical: 'Reflective Practice', volume: '15,', issue: '', editors: '', book: '', pages: '863-876.', publisher: '', link: 'https://doi.org/10.1080/14623943.2014.969695'},
        { code: 'P', bookbool: false, authors: 'Wagstaff, C. R. D. & Leech, J.', year: '2017', article: 'The value of strength-based approaches in SERE and sport psychology.', periodical: 'Military Psychology', volume: '27,', issue: '', editors: '', book: '', pages: '65-84.', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Quartiroli, A.', year: '2014', article: 'The perceived value of the association for applied sport psychology certification and certification exam: a survey of sport and exercise psychology professionals.', periodical: 'Athletic Insight', volume: '6', issue: '(3),', editors: '', book: '', pages: '185-199.', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Vosloo, J., & Quartiroli, A.', year: '2014', article: 'An international portrait of the sport and exercise psychology professional: Examining professional practice issues from a global perspective.', periodical: 'Athletic Insight', volume: '6', issue: '(3),', editors: '', book: '', pages: '', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Neil, R., Cropley, B., Wilson, K., & Faull, A.', year: '2013', article: 'Exploring the value of reflective practice interventions in applied sport psychology: Case studies with an individual athlete and a team.', periodical: 'Sport & Exercise Psychology Review', volume: '9,', issue: '', editors: '', book: '', pages: '42-57.', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Watson II, J. C., Lubker, J. R., Zakrajsek, R. A., & Quartiroli, A.', year: '2012', article: 'Internet usage patterns and ethical concerns in sport and exercise psychology.', periodical: 'Athletic Insight', volume: '4', issue: '(1),', editors: '', book: '', pages: '65-78.', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Quartiroli, A. & Zizzi, S.J.', year: '2011', article: 'Exploring and comparing the historical and developmental paths of FEPSAC and AASP: Two organizations for two continents.', periodical: 'Athletic Insight', volume: '3', issue: '(1),', editors: '', book: '', pages: '1-20.', publisher: '', link: ''},
        { code: 'P', bookbool: false, authors: 'Cropley, B., Hanton, S., Miles, A., & Niven, A.', year: '2010', article: 'The value of reflective practice in professional development: An applied sport psychology review.', periodical: 'Sports Science Review', volume: '19,', issue: '', editors: '', book: '', pages: '179-209.', publisher: '', link: 'https://doi.org/10.2478/v10237-011-0025-8'},
        { code: 'P', bookbool: false, authors: 'Cropley, B., Hanton, S., Miles, A., & Niven, A.', year: '2010', article: 'Exploring the relationship between effective and reflective practice in applied sport psychology.', periodical: 'The Sport Psychologist', volume: '24,', issue: '', editors: '', book: '', pages: '521-541.', publisher: '', link: 'https://doi.org/10.1123/tsp.24.4.521'},
        { code: 'P', bookbool: false, authors: 'Faull, A. & Cropley, B.', year: '2009', article: 'Reflective learning in sport: A case study of a senior level triathlete.', periodical: 'Reflective Practice', volume: '10,', issue: '', editors: '', book: '', pages: '325-339.', publisher: '', link: 'https://doi.org/10.1080/14623940903034655'},
        { code: 'P', bookbool: false, authors: 'Cropley, B., Miles, A., Hanton, S., & Anderson, A.', year: '2007', article: 'Improving the delivery of applied sport psychology support through reflective practice.', periodical: 'The Sport Psychologist', volume: '21,', issue: '', editors: '', book: '', pages: '475-494.', publisher: '', link: 'https://doi.org/10.1123/tsp.21.4.475'} 
    ]},
    { code: 'PW', name: 'Professionals Wellbeing', publications: [
        { code: 'PW', bookbool: true, authors: 'Quartiroli, A., Wagstaff, C. R. D. Zakrajsek, R.A., Knight, S. M., & Etzel, E. F.', year: '2021', article: 'The Role of Self-Care and Professional Quality of Life in Sustaining a Long-Lasting Career in Sport Psychology: A Qualitative Exploration.', periodical: '', volume: '', issue: '', editors: '', book: 'Journal of Applied Sport Psychology', pages: '', publisher: 'Advanced Online Publication', link: 'https://doi.org/f7bw'},
        { code: 'PW', bookbool: true, authors: 'Baldock, L., Cropley, B., Mellalieu, S. D., & Neil, R.', year: '2020', article: 'Stress and well-being of those operating in groups.', periodical: '', volume: '', issue: '', editors: 'R. J. Schinke & D. Hackfort (Eds.),', book: 'The Routledge international encyclopaedia of sport and exercise psychology', pages: '(pp. 620-634)', publisher: 'Routledge', link: ''},
        { code: 'PW', bookbool: false, authors: 'Cropley, B., Sellars, P., Mellalieu, S. D., Neil, R., Wagstaff, C., & Wadey, R.', year: '2019', article: 'Mental health and well-being of individuals working in performance sport.', periodical: 'The Sport & Exercise Scientist', volume: '59,', issue: '', editors: '', book: '', pages: '28-29.', publisher: '', link: ''},
        { code: 'PW', bookbool: false, authors: 'Cropley, B., Sellars, P., Mellalieu, S., Neil, R., Wagstaff, C., & Wadey, R.', year: '2020', article: 'Researcher’s corner: Exploring the mental health and well-being of individuals working in performance sport.', periodical: 'AASP Newsletter', volume: '', issue: '', editors: '', book: '', pages: '', publisher: '', link: 'https://appliedsportpsych.org/members/aasp-newsletters/january-2020/researchers-corner-exploring-the-mental-health-and-well-being-of-individuals-working-in-performance-sport/'},
        { code: 'PW', bookbool: false, authors: 'Quartiroli, A., Knight, S., Etzel, E., & Zakrajsek, R.A.', year: '2019', article: 'Fostering and Sustaining Professional Practice as a Contributor to Professional Quality of Life: The Perspectives of Senior-Level, Experienced Sport Psychologists.', periodical: 'The Sport Psychologist', volume: '33', issue: '(2),', editors: '', book: '', pages: '148-158.', publisher: '', link: 'https://doi.org/dtxs'},
        { code: 'PW', bookbool: false, authors: 'Quartiroli, A., Etzel, E., Knight, S., & Zakrajsek, R.A.', year: '2019', article: 'The Multifaceted Meaning of Sport Psychology Professional Quality of Life.', periodical: 'Journal of Clinical Sport Psychology', volume: '13', issue: '(4),', editors: '', book: '', pages: '645-667.', publisher: '', link: 'https://doi.org/dtxr'},
        { code: 'PW', bookbool: false, authors: 'Quartiroli, A., Wagstaff, C., & Etzel, E.', year: '2019', article: 'The professional quality of life of sport psychologists: confirming a novel model of professional wellbeing in of sport psychology consultants.', periodical: 'Professional Psychology: Research and Practice', volume: '50', issue: '(3),', editors: '', book: '', pages: '155-167.', publisher: '', link: 'https://doi.org/dt84'},
        { code: 'PW', bookbool: false, authors: 'Quartiroli, A., Etzel, E., Knight, S., & Zakrajsek, R.A.', year: '2019', article: 'Taking Care of Yourself to Take Care of Others:  The Experience of Globally Situated Experienced Sport Psychology Practitioners.', periodical: 'Journal of Applied Sport Psychology', volume: '31', issue: '(2),', editors: '', book: '', pages: '147-167.', publisher: '', link: 'https://doi.org/dzgm'},
        { code: 'PW', bookbool: false, authors: 'Hings, R. F., Wagstaff, C. R. D., Thelwell, R. C., Gilmore, S., & Anderson, V.', year: '2018', article: 'Emotional labor and professional practice in sports medicine and science.', periodical: 'Emotional labor and professional practice in sports medicine and science', volume: '28', issue: '(2),', editors: '', book: '', pages: '704-716.', publisher: '', link: ''},
        { code: 'PW', bookbool: false, authors: 'Hings, R. F., Wagstaff, C. R. D., Thelwell, R. C., Gilmore, S., & Anderson, V.', year: '2018', article: 'Professional challenges in elite sport: Composite vignettes on the emotional labor demands of sports medicine and science practitioners.', periodical: 'Psychology of Sport & Exercise', volume: '35,', issue: '', editors: '', book: '', pages: '66-73.', publisher: '', link: ''},
        { code: 'PW', bookbool: false, authors: 'Cropley, B., Baldock, L., Neil, R., Mellalieu, S., Wagstaff, C., & Wadey, R.', year: '2016', article: 'Coping with the demands of professional practice: Sport psychology consultants’ perspectives.', periodical: 'The Sport Psychologist', volume: '30,', issue: '', editors: '', book: '', pages: '290-302.', publisher: '', link: 'https://doi.org/10.1123/tsp.2015-0125'}       
    ]},
    { code: 'CSP', name: 'Cultural Sport Psychology', publications: [
        { code: 'CSP', bookbool: true, authors: 'Quartiroli, A., Vosloo, J., Schinke, R. J., Anderson, S. N., Fisher, L. A., & Giffin, C. E.', year: '2021', article: 'Sport psychology professionals’ perceptions of the roadblocks to cultural sport psychology.', periodical: '', volume: '', issue: '', editors: '', book: 'Sport, Exercise, and Performance Psychology', pages: '', publisher: 'Advance online publication', link: 'https://doi.org/f7bt'},
        { code: 'CSP', bookbool: false, authors: 'Quartiroli, A., Vosloo, J., & Anderson, S. N.*, Ditter, J. **, Keeley, M. **', year: '2021', article: 'The transnational experience of expatriating and repatriating sport psychology professionals: A cultural journey.', periodical: 'Psychology of Sport and Exercise', volume: '54', issue: '(101903),', editors: '', book: '', pages: '', publisher: '', link: 'https://doi.org/f7bv'},
        { code: 'CSP', bookbool: false, authors: 'Quartiroli, A., Vosloo, J., Anderson, S. N.*, Schinke, R., Fisher, L., & Middleton, T.', year: '2020', article: 'The Prism of Culture: Seeing through the Lens of Globally Situated Sport Psychology Professionals.', periodical: 'International Journal of Sport Psychology', volume: '51,', issue: '', editors: '', book: '', pages: '10.7352/IJSP.2020.51.', publisher: '', link: ''},
        { code: 'CSP', bookbool: false, authors: 'Quartiroli, A., Vosloo, J., Fisher, L., & Schinke, R.', year: '2020', article: 'Culturally Competent Sport Psychology: A Survey of the Current Status of Sport Psychology Professionals.', periodical: 'The Sport Psychologist', volume: '34', issue: '(3),', editors: '', book: '', pages: '242-253.', publisher: '', link: ' https://doi.org/d9qf'},
        { code: 'CSP', bookbool: false, authors: 'Lee, S., Quartiroli, A., Baumann, D., Harris, B., Watson, J. C., & Schinke, R. J.', year: '2020', article: 'Sport and exercise psychology professionals’ beliefs and behaviors regarding multicultural training.', periodical: 'International Journal of Sport Psychology', volume: '', issue: '', editors: '', book: '', pages: '', publisher: '', link: 'http://www.ijsp-online.com/journal/nextissue/35'}      
    ]},
    { code: 'OSP', name: 'Organizational Sport Psychology', publications: [
        { code: 'OSP', bookbool: false, authors: 'Wagstaff, C. R. D.', year: '2019', article: 'A commentary and reflections on the field of organizational sport psychology: Epilogue to the special issue.', periodical: 'Journal of Applied Sport Psychology', volume: '31,', issue: '', editors: '', book: '', pages: '134-146.', publisher: '', link: ''},
        { code: 'OSP', bookbool: false, authors: 'Wagstaff, C. R. D.', year: '2019', article: 'Taking stock of organizational psychology in sport: An introduction to the special issue.', periodical: 'Journal of Applied Sport Psychology', volume: '31,', issue: '', editors: '', book: '', pages: '1-6.', publisher: '', link: ''},
        { code: 'OSP', bookbool: false, authors: 'Gilmore, S., Wagstaff, C. R. D., & Smith, J.', year: '2018', article: "Sports psychology in the English Premier League: ‘It feels precarious and it is precarious’.", periodical: 'Work, Employment & Society', volume: '32,', issue: '', editors: '', book: '', pages: '426-435.', publisher: '', link: ''},
        { code: 'OSP', bookbool: false, authors: 'Wagstaff, C. R. D., Thelwell, R. C., & Gilmore, S.', year: '2016', article: 'When the show must go on; Examining repeated organizational change in elite sport.', periodical: 'Journal of Change Management', volume: '16', issue: '(1),', editors: '', book: '', pages: '38-54.', publisher: '', link: ''},
        { code: 'OSP', bookbool: false, authors: 'Wagstaff, C. R. D., Gilmore, S., & Thelwell, R. C.', year: '2015', article: 'Sport medicine and sport science practitioners’ experiences of organizational change.', periodical: 'Scandinavian Journal of Medicine and Science in Sport', volume: '25', issue: '(5),', editors: '', book: '', pages: '685-698.', publisher: '', link: ''},
        { code: 'OSP', bookbool: false, authors: 'Fletcher, D., & Wagstaff, C. R. D.', year: '2009', article: 'Organizational psychology in elite sport; Its emergence, application, and future.', periodical: 'Psychology of Sport and Exercise', volume: '4,', issue: '', editors: '', book: '', pages: '427-434.', publisher: '', link: ''}      
    ]},
    { code: 'SP', name: 'Sport Pscyhology', publications: [] }
]