import { Member } from './member';

export const MEMBERS: Member[] = [
    { name: 'Ale Quartiroli',
        firstName: 'Ale',
        lastName: 'Quartiroli',
        certs: 'PhD, CMPC, CPsychol, NCC',
        bio: "Ale is currently an Associate Professor of Psychology at the UW – La Crosse (US) as well as a Visiting Reader at the University of Portsmouth (UK). Originally from Italy, Ale studied psychology (UG) and sport conflict mediation (Executive Master) in Italy, athletic coaching education (MS), counseling (MA), and sport and exercise psychology (PhD), in the United States and research methodology (MS) in Spain. Ale is a certified mental performance consultant (CMPC) with the Association for Applied Sport Psychology, a national certified counselor (NCC) with the National Board of Certified Counselors, a Chartered Psychologist (CPsych) and an approved supervisor with the British Psychological Society. Ale is actively involved in many international professional organization (e.g., AASP, FEPSAC, ISSP), for some of which he also had roles in the leadership. Ale’s main areas of professional interest expand around the idea of supporting future and current professional in their development and practice. I am particularly interested in understanding and improving the self-care and wellbeing of helping professionals, especially sport and performance psychology professionals and to support future and current practitioners to develop personally and professionally within the sport psychology context while providing an ethical, competent, culturally competent, and effective service delivery. I have also recently started to explore new lines of research focused on professionals’ emotions and attitudes as well as organizational behavior. In addition to my academic role, I am also actively involved in applied practice with athletes and exercises in my surrounding community and in the supervision of applied professional practice of neophyte sport psychology professionals.",
        email: "aquartiroli@uwlax.edu",
        photoPath:'./assets/photos/AleQuartiroli.jpeg',
        externalLinks: {
            institutional: 'https://www.uwlax.edu/profile/aquartiroli/',
            research: ['https://www.researchgate.net/profile/Alessandro-Quartiroli-2', 'https://scholar.google.com/citations?user=iLOovrwAAAAJ&hl=en&oi=ao'] }
    },
    { name: 'Chris Wagstaff',
        firstName: 'Chris',
        lastName: 'Wagstaff',
        certs: 'CPsychol, AFBPsS, HCPC, EuroPsy, CSci, fHEA',
        bio: "Chris is a performance psychologist who divides his time between research, consultancy, and the training and development of practitioners. Chris holds positions as a Reader in Applied Psychology at the University of Portsmouth, UK and as a Senior Performance Psychologist with Changing Minds UK, and was previously Head of Performance Psychology for the English Institute of Sport. Chris holds Editor and Associate Editor positions at JASP, SEPR, IJSEP, and CSSEP and in 2016 developed the UK's first non-professional society training pathway for Sport Psychologists to be approved by the Health and Care Professions Council. Chris researches the psychology of elite performance, principally through an organisational or systems lens, and is passionate about using this work to support the training and development of practitioners. This work has been presented in over 100 peer-reviewed journal articles and book chapters, He has also edited the first book (2017, Routledge) and a special issue of JASP (2019) on organisational sport psychology.",
        email: "chris.wagstaff@port.ac.uk",
        photoPath:'./assets/photos/ChrisWagstaff.png',
        externalLinks: {
            institutional: 'https://www.port.ac.uk/about-us/structure-and-governance/our-people/our-staff/chris-wagstaff',
            research: ['https://www.researchgate.net/profile/Christopher-Wagstaff', 'https://scholar.google.com/citations?user=D8JDBjgAAAAJ&hl=en&oi=sra'] },
    },
    { name: 'Beckie Hings',
        firstName: 'Beckie',
        lastName: 'Hings',
        certs: 'PhD',
        bio: "Beckie is a Lecturer in Sport, Health and Exercise Sciences (Psychology) and member of the Centre for Health and Wellbeing across the Lifecourse at Brunel University London. Beckie received her undergraduate degree in Sport and Exercise Science at the University of Portsmouth where she continued to study for her PhD in Organisation Studies at Portsmouth Business School. As an early career researcher, Beckie has continued to develop her scholarly expertise about the everyday experiences, learning, and challenges of sports medicine and science practitioners, especially in relation to emotional labour and wellbeing. Adopting a psychosocial perspective, Beckie’s research intends to support future and current sports medicine and science practitioners with navigating the complexities, paradoxes, and high-performance environments encountered as part of their professional practice. Beckie supervises Doctoral Researchers at Brunel University London and Professional Doctorate (Sport and Exercise Psychology) students at the University of Portsmouth. Beckie has also provided research consultancy to the English Institute of Sport.",
        email: "rebecca.hings@brunel.ac.uk",
        photoPath:'./assets/photos/BeckieHings.jpeg',
        externalLinks: {
            institutional: 'https://www.brunel.ac.uk/people/rebecca-hings',
            research: ['https://scholar.google.com/citations?user=_elHgocAAAAJ&hl=en&oi=ao'] },
    },
    { name: 'Brendan Cropley',
        firstName: 'Brendan',
        lastName: 'Cropley',
        certs: 'Ph.D., C.Sci., FBASES, FHEA',
        bio: "Brendan is the Head of the Centre for Football Research in Wales and the Coaching Science Lead for the Welsh Institute of Perfomance Science Research Steering Group. His research interests focus on the development of professional practice in different disciplines, specifically sport coaching and sport psychology. These interests include examining the value of, and improving, education and development pathways. He is particularly interested in reflective practice and the potential it has for developing effective practice and facilitating human flourishing. More recently, he has become interested in researching the development of life skills through sport and the psychology of performance in coaches and athletes alike focusing on mental health and well-being. Brendan has made a significant contribution to the Sport & Exercise Sciences, particularly in the area of sport psychology and sport coach education. He has provided a range of consultancy services to elite athletes, coaches, and National Governing Bodies of sport as well as having an established research profile that has helped to shape training and development programmes in the sport sciences (e.g., BASES Sport & Exercise Psychology Accreditation Route) and sport coaching (e.g., FAW / UEFA A Licence). He has also acted as a professional practice supervisor for British Association of Sport & Exercise Science (BASES) since 2008, and provided informal mentoring to trainee practitioners in a range of different sport science disciplines. This contribution was recognised by the BASES who awarded Brendan Fellowship status in 2014. Brendan has been a BASES Accredited Sport & Exercise Scientist (Psychology) since 2007, a Chartered Scientist since 2014, and is a UEFA A Licence coach, coach educator, and mentor.",
        email: "brendan.cropley@southwales.ac.uk",
        photoPath:'./assets/photos/BrendanCropley.jpg',
        externalLinks: {
            institutional: 'https://www.southwales.ac.uk/research/research-news/research-profile-professor-brendan-cropley/',
            research: ['https://www.researchgate.net/profile/Brendan-Cropley', 'https://scholar.google.com/citations?user=wwOOqVUAAAAJ&hl=en&oi=ao'] },
    },
    { name: 'Jana Fogaca',
        firstName: 'Jana',
        lastName: 'Fogaca',
        certs: 'PhD, CMPC',
        bio: "Jana is an Assistant Professor in the Kinesiology Department at California State University, Long Beach. She received her undergraduate degree in Psychology from the Federal University of RS (Brazil). She also has two master's degrees, one in Sport and Exercise Psychology from University of Jyväskylä (Finland) and one in Counseling from West Virginia University, where she also completed her PhD in Sport and Exercise Psychology. Her research interests include professional development in sport psychology, applied sport psychology, and positive youth development. She hopes to contribute to the continuous improvement of the sport and exercise psychology profession through her research in supervision and training and in applied sport psychology. She is also interested in teaching mental skills to young exercisers to improve their well-being and success beyond sports.",
        email: "jana.fogaca@csulb.edu",
        photoPath:'./assets/photos/JanaFogaca.jpg',
        externalLinks: {
            institutional: '',
            research: ['https://www.researchgate.net/profile/Jana-Fogaca', 'https://scholar.google.com/citations?user=0t35B5wAAAAJ&hl=en&oi=ao'] },
    },
]